apiVersion: v1
kind: Namespace
metadata:
  name: nginx-frontend

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-configmap
  namespace: nginx-frontend
data:
  index.html: |
    "Hello world!!!!!!!!!!!!!!!!"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-frontend
  labels:
    app: nginx-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-env
  template:
    metadata:
      labels:
        app: nginx-env
    spec:
      containers:
      - name: nginx-01
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-file
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: index-file
        configMap:
          name: index-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-frontend
spec:
  selector:
    app: nginx-env
  ports:
  - port: 9999
    targetPort: 80
  type: LoadBalancer
 
